### ISSUE TITLE
Save binary

### ISSUE THREAD

**Issue by ruudboon** [ArminJo/arduino-test-compile#13]
Thnx for this awesome action. 
I'm wondering if it's possible to generate and keep the compiled binary as well. 
I would like to save it using github artifact and use that binary on a release (working on OTA that will fetch the binary from my release page).

**Comment by ArminJo** [comment]
The **generated .bin and .elf files** can be found in the example directory or in `/home/runner/<sketch-name>` for files not residing in a directory with the same name.
