### ISSUE TITLE
many boards x many defines

### ISSUE THREAD

**Issue by i-make-robots** [ArminJo/arduino-test-compile#18]
Hi!  Your Action looks great!

I've got firmware that runs on ... 6 different boards (defined in code and set board).  It also has up to 7 different modes (defined in code) for each of those boards.  I want to have a matrix of every valid combination so that my edits are at least compile-safe for every combination.  Your script looks really close to what I'm after.  

Can you confirm, please?

**Comment by ArminJo** [comment]
Hi,
I added [documentation](https://github.com/ArminJo/arduino-test-compile#one-board-with-2x2-compile-parameter-matrix) for this case.

**Comment by i-make-robots** [comment]
Thank you!!

**Comment by i-make-robots** [comment]
My goal is to test my sketch against several boards and configurations.   Is there a wild card to exclude all examples?

**Comment by i-make-robots** [comment]
https://github.com/ArminJo/arduino-test-compile#single-program-using-sketch-names-parameter still mentions examples, so it has me uncertain.

**Comment by ArminJo** [comment]
The parameter name examples-build-properties is historic just use [sketch-names](https://github.com/ArminJo/arduino-test-compile#sketch-names)

**Comment by i-make-robots** [comment]
I wish I was grokking this...
What if the define is like "#define A B"?  -DA=B?  -DA B?

**Comment by ArminJo** [comment]
I never defined macros at the compiler commandline.

**Comment by i-make-robots** [comment]
fwiw, the repo in question is https://github.com/MarginallyClever/Makelangelo-firmware
in configure.h there are several defines for BOARD_TYPE and MACHINE_STYLE.  I'm trying to change these at compile time and the board type.

**Comment by ArminJo** [comment]
I guess the issue is solved 😀
