### ISSUE TITLE
arduino-cli lib install dependency strictness

### ISSUE THREAD

**Issue by tobozo** [ArminJo/arduino-test-compile#25]
Hey and thanks for the awesome project !

I'm getting an issue with a couple of libraries I'm importing using `required-libraries`, the installation of the required libraries fails although I know those are valid library names.

After a quick investigation, I found out those library have a poisonous `depends` entry in their library.properties file, sometimes listing a library name that isn't in the registry, sometimes listing an ambigous name, and deferring the failure even though the main library has been downloaded.

Here's a couple of examples: [M5Stack](https://github.com/m5stack/M5Stack/blob/master/library.properties) and [M5StickC](https://github.com/m5stack/M5StickC/blob/master/library.properties).

Here's a screenshot of the failure for the `M5StickC` library:

![image](https://user-images.githubusercontent.com/1893754/138163186-cf88cea8-b74a-46a0-b191-0bd96dde9cd4.png)

I went looking for a way to trigger the `--no-deps` options of `arduino-cli lib install` using this github action and found none, so here I am writing this feature request :wink: 

An action option like `lib-dep-resolver: false` would be neat to handle those situations.

be well

**Comment by ArminJo** [comment]
Thanks, I forgot one line.
Please rerun the action again.
