### ISSUE TITLE
Use comma to separate list elements

### ISSUE THREAD

**Issue by Legion2** [ArminJo/arduino-test-compile#3]
Make it uniform how lists are specified.

Arduino libraries should be separated with comma, because spaces are allowed in library names but commas not see [library-specification](https://arduino.github.io/arduino-cli/library-specification/#libraryproperties-file-format).

Arduino sketches should also be separated using commas.

**Comment by ArminJo** [comment]
Thanks!!!
In the new version I changed `required-libraries` from **space** to **comma* separated list 
and you can use a comma separated exclude list :-)
