### ISSUE TITLE
Support examples-inlcude

### ISSUE THREAD

**Issue by Legion2** [ArminJo/arduino-test-compile#4]
I want to explicitly state which sketches should be compiled. Then you can directly see in the workflow definition which examples are compiled. This also reduces duplicate specification, when you have sketches for specific boards which must be excluded from every other boards compilation.

**Comment by ArminJo** [comment]
I understand and will have a look...

**Comment by ArminJo** [comment]
You do not want to specify full pathname I guess?

**Comment by Legion2** [comment]
Would be nice

**Comment by ArminJo** [comment]
Please test it.
see https://github.com/ArminJo/arduino-test-compile#multiple-boards-with-parameter

**Comment by Legion2** [comment]
@ArminJo I can't find the `examples-inlcude` option. When you force push to master, it's hard to track the changes you made.

**Comment by ArminJo** [comment]
You are right but I want avoid an endless commit log!
The option is `sketch-names`

**Comment by Legion2** [comment]
Ok, cool can you trim the values after splitting at `,` so it is possible to specify the list using [this syntax](https://github.com/Legion2/CorsairLightingProtocol/blob/arduino-test-compile/.github/workflows/push.yml#L24-L35). This introduces white space for each new line.

**Comment by ArminJo** [comment]
Done :-)

**Comment by Legion2** [comment]
Cool, thanks for your help.
