### ISSUE TITLE
Readme has wrong examples-build-properties description

### ISSUE THREAD

**Issue by Legion2** [ArminJo/arduino-test-compile#5]
The description of [examples-build-properties](https://github.com/ArminJo/arduino-test-compile/blob/3e6885559e60747266c85c396584d696cba6da5b/README.md#examples-build-properties) in the readme does not explain format of the configuration and the example makes no sense. Looks like the example was copy-pasted from `examples-exclude`.

**Comment by Legion2** [comment]
The EXAMPLES_BUILD_PROPERTIES is printed without the first `{`
https://github.com/ArminJo/arduino-test-compile/blob/3e6885559e60747266c85c396584d696cba6da5b/arduino-test-compile.sh#L190

**Comment by ArminJo** [comment]
THANKS,
readme is fixed.

**Comment by Legion2** [comment]
also the json is not parsed correctly, use jq instead of regex.

**Comment by ArminJo** [comment]
what means "not correctly", it works for all my tests.

> The EXAMPLES_BUILD_PROPERTIES is printed without the first {
is fixed

**Comment by Legion2** [comment]
You can not specify a yaml object as argument to the action as it is suggested by the updated readme:
`Your workflow file was invalid: The pipeline is not valid. .github/workflows/push.yml (Line: 40, Col: 13): A mapping was not expected`

**Comment by Legion2** [comment]
https://github.com/Legion2/CorsairLightingProtocol/runs/543092637?check_suite_focus=true#step:4:99 here is the output of my workflow and the first `{` is not printed

**Comment by Legion2** [comment]
It also happens in your workflow https://github.com/ArminJo/Arduino-RobotCar/runs/542840082?check_suite_focus=true#step:3:112

**Comment by ArminJo** [comment]
The trailing { was fixed a few mitutes ago
https://github.com/ArminJo/Github-Actions/runs/543130754?check_suite_focus=true#step:4:93

**Comment by ArminJo** [comment]
> You can not specify a yaml object as argument to the action as it is suggested by the updated readme:
> `Your workflow file was invalid: The pipeline is not valid. .github/workflows/push.yml (Line: 40, Col: 13): A mapping was not expected`

Can you be more specific?

**Comment by Legion2** [comment]
I tried the examples-build-properties syntax as described in the readme:
```yaml
examples-build-properties:
 WhistleSwitch:
    -DDEBUG
    -DFREQUENCY_RANGE_LOW
  SimpleFrequencyDetector:
    -DINFO
```
https://github.com/Legion2/CorsairLightingProtocol/blob/f6ba148ba2efea0ac8030bb91e6a657601f9a403/.github/workflows/push.yml#L39-L46
and got the error 
https://github.com/Legion2/CorsairLightingProtocol/runs/543117357?check_suite_focus=true

**Comment by ArminJo** [comment]
I seems, that directly specifying at with: is not possible.
in the readme there is:
`examples-build-properties: ${{ toJson(matrix.examples-build-properties) }}`

or it is specified in the include section.
```
        include:
...
            examples-build-properties:
              WhistleSwitch:
                -DDEBUG
                -DTRACE
```

I found no way to specify it directly 👎

**Comment by ArminJo** [comment]
I found it :-)
Use escaped double quotes.

`examples-build-properties: "{ \"WhistleSwitch\": \"-DDEBUG -DFREQUENCY_RANGE_LOW\", \"SimpleFrequencyDetector\": \"-DINFO\" }"`

**Comment by Legion2** [comment]
I used singe quotes and then it worked:
```yaml
examples-build-properties: '{"DebugSketch": "-DDEBUG -DVERBOSE -DPRINT_COMMAND=true -DPRINT_RESPONSE=true -DPRINT_LOOP=true -DPRINT_UPDATE=true"}'
```
https://github.com/Legion2/CorsairLightingProtocol/blob/arduino-test-compile/.github/workflows/push.yml#L39

**Comment by Legion2** [comment]
can you update the readme, because the current example syntax does not work

**Comment by ArminJo** [comment]
What exactly is wrong?

**Comment by Legion2** [comment]
When applying the configuration as shown in the readme directly in the `with:` section of the action it won't work:
![image](https://user-images.githubusercontent.com/12752323/77962234-8a2f9580-72db-11ea-91b0-d4d40c59dadc.png)
But the readme doesn't tell you that. It should contain information about the json format used to encode this information.

**Comment by ArminJo** [comment]
Now I see

**Comment by ArminJo** [comment]
Thanks! I hope it is clearer now.
