### ISSUE TITLE
The release 2.0.0 has a typo in the tag name

### ISSUE THREAD

**Issue by Legion2** [ArminJo/arduino-test-compile#6]
The version tag is `v.2.0.0` but should be `v2.0.0`.

**Comment by ArminJo** [comment]
Oh sch...
Thanks!!!!

**Comment by Legion2** [comment]
The version tag is `v.2.0.0` again and my build break :(

**Comment by ArminJo** [comment]
Schit, ich lern das nie.
Nimm besser die v2.2.0
Danke
Armin

**Comment by Legion2** [comment]
Am besten releases nicht mehr ändern
